### ISSUE TITLE
Categories not showing correctly

### ISSUE THREAD

**Issue by africancup** [qdzhang/hugo-notepadium-mod#12]
I have added categories to the frontmatter of some pages, but the 'Categories' page shows the same thing as the home page, like this [page](https://www.littlezhang.com/categories/), just with the title 'Categories'. When I use the same config.toml on the hugo-notepadium theme, I see the 'Categories' page as it should be, like this [page](https://examplesite.lvv.me/categories/).

**Comment by qdzhang** [comment]
Thanks for pointing out it. And there were some other similar errors in taxonomies, but I didn't notice them previously 😲. I have fixed them all a moment ago.
