### ISSUE TITLE
Error building site: render of "taxonomy" failed

### ISSUE THREAD

**Issue by africancup** [qdzhang/hugo-notepadium-mod#9]
Hugo Version:  hugo v0.83.1+extended linux/amd64 BuildDate=unknown
Build Command: REPLACE_WITH_YOUR_HUGO_BUILD_CMD

Hi, first please could you instruct me on how to get the "Hugo build command" so I can post it here. I get the following error when I run `hugo -D server`.

```
[cup@machine ~/website]$ hugo -D server
Start building sites … 
ERROR 2021/06/11 23:36:16 render of "taxonomy" failed: "/home/cup/website/themes/hugo-notepadium-mod/layouts/_default/tag.terms.html:12:26": execute of template failed: template: _default/tag.terms.html:12:26: executing "main" at <len (index $.Site.Taxonomies.tags.ByCount 0).Pages>: error calling len: reflect: call of reflect.Value.Type on zero Value
Built in 179 ms
Error: Error building site: failed to render pages: render of "taxonomy" failed: "/home/cup/website/themes/hugo-notepadium-mod/layouts/_default/tag.terms.html:12:26": execute of template failed: template: _default/tag.terms.html:12:26: executing "main" at <len (index $.Site.Taxonomies.tags.ByCount 0).Pages>: error calling len: reflect: call of reflect.Value.Type on zero Value
```

The problem is in the following lines (12,13) in the file */home/cup/website/themes/hugo-notepadium-mod/layouts/_default/tag.terms.html*:

```
{{- $max := add (len (index $.Site.Taxonomies.tags.ByCount 0).Pages) 1 -}}
{{- $min := len (index $.Site.Taxonomies.tags.ByCount.Reverse 0).Pages -}} 
```

I have got my website working by replacing those lines by:

```
{{- $max := 1 -}}
{{- $min := 0 -}}
```

so I am certain those lines are the only issue I haven't come up with a proper solution because I have no experience with webdev.

**Comment by qdzhang** [comment]
This error happens because there may be no tags in your site. And add tags in the [front matter](https://gohugo.io/content-management/front-matter#readout) of posts should solve it, I guess.

And also, you can keep your changes. They will work fine, but as a result, the tags page will **not** show tags with different font sizes according to the frequencies, like this:
![2021-06-12_165105_192921115](https://user-images.githubusercontent.com/29973818/121771184-6c78e400-cba0-11eb-85e6-545eb76a1a8a.png)

**Comment by africancup** [comment]
Thanks for the quick and clear response, adding a tag to the front matter of at least one of my posts fixed the issue.

I have only used `title` and `date` in my front matter so far - this theme provides much more!
